// ─── Skill Tree Data Module ─────────────────────────────────────────
// Generated by scripts/build-skill-trees.ts from:
//   - data/zrenderer-resources/data/skilltreeview.txt (positions/prereqs)
//   - data/database/skills.json (IDs/descriptions)
//   - data/rathena/skill_db.yml (cast times/SP costs)

import skillTreeData from "../../data/database/skill-trees.json";

// ─── Types ──────────────────────────────────────────────────────────

export interface SkillTreeNode {
  aegisName: string;
  id: number;
  position: number;
  row: number;
  col: number;
  maxLevel: number;
  prereqs: number[];  // prerequisite positions within same job tree
  name: string;
  namePt: string;
  description: string;
  type: string;
  targetType: string;
  spCost: number[];
  castTime: number[];
  fixedCast: number[];
  cooldown: number[];
}

export interface JobTree {
  jobId: number;
  jobName: string;
  skills: SkillTreeNode[];
}

// ─── Data access ────────────────────────────────────────────────────

const data = skillTreeData as {
  trees: Record<string, SkillTreeNode[]>;
  chains: Record<string, number[]>;
  jobNames: Record<string, string>;
};

export function getJobChain(classId: string): number[] {
  return data.chains[classId] || [];
}

export function getSkillTreeForClass(classId: string): JobTree[] {
  const chain = getJobChain(classId);
  return chain
    .map((jobId) => {
      const skills = data.trees[jobId.toString()];
      if (!skills) return null;
      return {
        jobId,
        jobName: data.jobNames[jobId.toString()] || `Job ${jobId}`,
        skills,
      };
    })
    .filter((t): t is JobTree => t !== null);
}

export function getSkillTree(jobId: number): SkillTreeNode[] {
  return data.trees[jobId.toString()] || [];
}

export function getJobName(jobId: number): string {
  return data.jobNames[jobId.toString()] || `Job ${jobId}`;
}

export function skillIconUrl(skillId: number): string {
  return `https://static.divine-pride.net/images/skill/${skillId}.png`;
}

export function getAllClassIds(): string[] {
  return Object.keys(data.chains);
}
