// ─── Skill Tree Data Module ─────────────────────────────────────────
// Generated by scripts/build-skill-trees.ts from:
//   - data/zrenderer-resources/data/skilltreeview.txt (positions/prereqs)
//   - data/database/skills.json (IDs/descriptions)
//   - data/rathena/skill_db.yml (cast times/SP costs)

import skillTreeData from "../../data/database/skill-trees.json";

// ─── Types ──────────────────────────────────────────────────────────

export interface SkillTreeNode {
  aegisName: string;
  id: number;
  position: number;
  row: number;
  col: number;
  maxLevel: number;
  prereqs: number[];  // prerequisite positions within same job tree
  name: string;
  namePt: string;
  description: string;
  type: string;
  targetType: string;
  spCost: number[];
  castTime: number[];
  fixedCast: number[];
  cooldown: number[];
}

export interface JobTree {
  jobId: number;
  jobName: string;
  skills: SkillTreeNode[];
}

// ─── Data access ────────────────────────────────────────────────────

const data = skillTreeData as {
  trees: Record<string, SkillTreeNode[]>;
  chains: Record<string, number[]>;
  jobNames: Record<string, string>;
};

export function getJobChain(classId: string): number[] {
  return data.chains[classId] || [];
}

export function getSkillTreeForClass(classId: string): JobTree[] {
  const chain = getJobChain(classId);
  return chain
    .map((jobId) => {
      const skills = data.trees[jobId.toString()];
      if (!skills) return null;
      return {
        jobId,
        jobName: data.jobNames[jobId.toString()] || `Job ${jobId}`,
        skills,
      };
    })
    .filter((t): t is JobTree => t !== null);
}

export function getSkillTree(jobId: number): SkillTreeNode[] {
  return data.trees[jobId.toString()] || [];
}

export function getJobName(jobId: number): string {
  return data.jobNames[jobId.toString()] || `Job ${jobId}`;
}

export function skillIconUrl(skillId: number): string {
  return `https://static.divine-pride.net/images/skill/${skillId}.png`;
}

export function getAllClassIds(): string[] {
  return Object.keys(data.chains);
}

// ─── Max Skill Points per Job Tier ─────────────────────────────────
// Points available = max job level - 1

const JOB_MAX_POINTS: Record<number, number> = {
  0: 9,       // Novice (Job Lv 10)
  // 1st classes (Job Lv 50)
  1: 49, 2: 49, 3: 49, 4: 49, 5: 49, 6: 49,
  // 2nd classes (Job Lv 50)
  7: 49, 8: 49, 9: 49, 10: 49, 11: 49, 12: 49,
  14: 49, 15: 49, 16: 49, 17: 49, 18: 49, 19: 49, 20: 49,
  // Transcendent 2nd classes (Job Lv 70)
  4008: 69, 4009: 69, 4010: 69, 4011: 69, 4012: 69, 4013: 69,
  4015: 69, 4016: 69, 4017: 69, 4018: 69, 4019: 69, 4020: 69, 4021: 69,
  // 3rd classes (Job Lv 70)
  4054: 69, 4055: 69, 4056: 69, 4057: 69, 4058: 69, 4059: 69,
  // Expanded
  23: 98,     // Super Novice (Job Lv 99)
  24: 49, 25: 49,
  4046: 49, 4047: 69, 4049: 69,
};

export function getMaxSkillPoints(jobId: number): number {
  return JOB_MAX_POINTS[jobId] || 49;
}
